name: Test GHA Command

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-gha:
    name: Test sb gha command
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sb-go repository
        uses: actions/checkout@v5
        with:
          path: sb-go

      - name: Checkout Saltbox repository
        uses: actions/checkout@v5
        with:
          repository: saltyorg/Saltbox
          path: saltbox

      - name: Extract Go version from go.mod
        id: go_version
        working-directory: sb-go
        run: echo "version=$(grep '^go ' go.mod | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.go_version.outputs.version }}
          cache-dependency-path: sb-go/go.sum

      - name: Tune GitHub-hosted runner network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Create required directories
        run: sudo mkdir -p /srv/git

      - name: Set ownership
        run: sudo chown -R runner:runner /srv/git

      - name: Symlink Saltbox repository
        run: ln -s $GITHUB_WORKSPACE/saltbox /srv/git/saltbox

      - name: Run tidy
        working-directory: sb-go
        run: make tidy

      - name: Run tests
        working-directory: sb-go
        run: make test

      - name: Build sb binary
        working-directory: sb-go
        run: |
          make build
          sudo cp build/sb /usr/local/bin/sb
          /usr/local/bin/sb version
      - name: Print pip dependencies
        run: cat /srv/git/saltbox/requirements/requirements-saltbox.txt

      - name: Run sb gha command
        run: |
          set -x  # Enable command tracing
          /usr/local/bin/sb gha
          echo "Exit code: $?"

      - name: Verify installation
        run: |
          echo "=== Checking Python venv ==="
          ls -la /srv/ansible/venv/bin/
          /srv/ansible/venv/bin/python3 --version
          /srv/ansible/venv/bin/ansible --version

      - name: Check saltbox.fact
        run: |
          echo "=== Checking saltbox.fact ==="
          ls -la /srv/git/saltbox/ansible_facts.d/saltbox.fact
          /srv/git/saltbox/ansible_facts.d/saltbox.fact

      - name: Test Ansible syntax check
        run: |
          cd /srv/git/saltbox
          /srv/ansible/venv/bin/ansible-playbook saltbox.yml --syntax-check
